services:
  - type: web
    name: mnist-app
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt --no-cache-dir --force-reinstall
    startCommand: |
      waitress-serve --port=$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
    healthCheckPath: /health
    plan: free