services:
  - type: web
    name: mnist-classifier
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
    staticDir: static/uploads/